# Generated by Django 4.2.20 on 2025-04-24 00:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("transactions", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="transaction",
            name="category",
            field=models.CharField(
                blank=True,
                choices=[
                    ("housing", "Housing"),
                    ("transportation", "Transportation"),
                    ("food", "Food & Dining"),
                    ("utilities", "Utilities"),
                    ("healthcare", "Healthcare"),
                    ("entertainment", "Entertainment"),
                    ("shopping", "Shopping"),
                    ("education", "Education"),
                    ("savings", "Savings"),
                    ("other", "Other"),
                ],
                max_length=20,
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="transaction",
            name="description",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.DeleteModel(
            name="MonthlyBudget",
        ),
    ]
