# Generated by Django 4.2.20 on 2025-04-22 16:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("transactions", "0002_monthlybudget"),
    ]

    operations = [
        migrations.DeleteModel(name="MonthlyBudget",),
    ]
