# Generated by Django 4.2.20 on 2025-04-24 14:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("budgets", "0001_initial"),
    ]

    operations = [
        migrations.AddIndex(
            model_name="budget",
            index=models.Index(
                fields=["user", "-created_at"], name="budgets_bud_user_id_60005f_idx"
            ),
        ),
    ]
