# Generated by Django 4.2.20 on 2025-04-24 21:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("budgets", "0002_budget_budgets_bud_user_id_60005f_idx"),
    ]

    operations = [
        migrations.AlterField(
            model_name="budget",
            name="amount",
            field=models.DecimalField(decimal_places=2, max_digits=10),
        ),
        migrations.AlterField(
            model_name="budgetitem",
            name="amount",
            field=models.DecimalField(decimal_places=2, max_digits=10),
        ),
    ]
