# Generated by Django 4.2.20 on 2025-04-22 15:54

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('budgets', '0004_item_delete_entry_budget_amount_budget_description_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='budget',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='budget',
            name='user',
            field=models.ForeignKey(to = settings.AUTH_USER_MODEL,on_delete = django.db.models.deletion.CASCADE,related_name = 'budgets',null = True,),
            preserve_default=False,
        ),
    ]
